name: deploySecrets
on: push
jobs:
  firts_job:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimesecreto
        run: echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: variable
        run: echo "${{ env.NAME }}"