name: deploySecrets
on: push
jobs:
  firts_job:
    strategy:
      matrix:
        version:  "ubuntu-latest"]
    runs-on: ${{ matrix.version }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Imprimesecreto
        run: echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: variable
        run: echo "${{ vars.NAME }}"
      
      - name: redis
        run: redis-cli -h localhost -p 6379
      
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18 