name: deploySecrets
on: push
jobs:
  build:
    strategy:
      matrix:
        version: [ "ubuntu-latest"]
    runs-on: ${{ matrix.version }}
    steps:
      - name: variable
        run: echo "${{ vars.NAME }}"
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18 
      
      - name: instalar dependencias
        run: npm install
      
      - name: ejecutar test
        run: npm run test
      
      - name: build
        run: npm run build
      
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    enviroment:
      name: github-pages
      ulr: ${{ steps.deployPages.outputs.page_url }}
    steps:
      - name: deploy
        run: echo "Desplegando"
      - name: deployapages
        id: deployPages
        uses: actions/deploy-pages@v4


    