name: deploySecrets
on: push
jobs:
  firts_job:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimesecreto
        run: echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: variable
        run: echo "${{ vars.NAME }}"
      
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18 