name: deploySecrets
on: push
jobs:
  firts_job:
    strategy:
      matrix:
        version: ["24.04-02", "24.04-01"]
    runs-on: ubuntu- ${{ matrix.version }}
    steps:
      - name: Imprimesecreto
        run: echo "${{ secrets.TOKEN_SECRET }}"
      
      - name: variable
        run: echo "${{ vars.NAME }}"
      
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: 18 